---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pos
  namespace: backend
  labels:
    app: api-pos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pos
  template:
    metadata:
      labels:
        app: api-pos
    spec:
      containers:
      - name: api-pos
        image: adiatma/api-pos:latest
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: "1m"
            memory: "4Mi"
        env:
         - name: DATABASE_HOST
           value: 10.2.1.25:5432
         - name: DATABASE_NAME
           value: api-pos-db
         # get data from api-pos-secret
         - name: DATABASE_USERNAME
           valueFrom:
             secretKeyRef:
               name: api-pos-secret
               key: DATABASE_USERNAME
         - name: DATABASE_PASSWORD
           valueFrom:
             secretKeyRef:
               name: api-pos-secret
               key: DATABASE_PASSWORD
